version: '3.8'
services:
  tomcat:
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - "8080:8080"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - "80:80"

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: student_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
